### ISSUE TITLE
Verify Object learners can recognize objects in dynamic situations

### ISSUE THREAD

**Issue by LichMaster98** [isi-vista/adam#963]
After a discussion, I currently believe our object learners will fail to recognize objects in dynamic situations because they are unable to handle temporally scoped edges. We should see if this is the case and if so update the object learners to be able to handle this.

**Comment by paynesa** [comment]
When running `log_experiment` with `m13_complete` curriculum and the integrated learner in English, we encounter the following error while learning colour attributes: 
```Traceback (most recent call last):
  File "/home/paynesa/adam/adam/experiment/log_experiment.py", line 391, in <module>
    parameters_only_entry_point(log_experiment_entry_point)
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/vistautils/parameters_only_entrypoint.py", line 43, in parameters_only_entry_point
    args=sys.argv[1:],
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/vistautils/parameters_only_entrypoint.py", line 73, in _real_parameters_only_entry_point
    main_method(params)
  File "/home/paynesa/adam/adam/experiment/log_experiment.py", line 144, in log_experiment_entry_point
    load_learner_state=params.optional_existing_file("learner_state_path"),
  File "/home/paynesa/adam/adam/experiment/__init__.py", line 252, in execute_experiment
    offset=starting_point,
  File "/home/paynesa/adam/adam/learner/integrated_learner.py", line 126, in observe
    sub_learner.learn_from(current_learner_state, offset=offset)
  File "/home/paynesa/adam/adam/learner/template_learner.py", line 296, in learn_from
    self._learning_step(preprocessed_input, thing_whose_meaning_to_learn)
  File "/home/paynesa/adam/adam/learner/subset.py", line 209, in _learning_step
    for previous_pattern_hypothesis in previous_pattern_hypotheses
  File "/home/paynesa/adam/adam/learner/subset.py", line 210, in <listcomp>
    for hypothesis_from_current_perception in hypotheses_from_current_perception
  File "/home/paynesa/adam/adam/learner/relations.py", line 130, in _update_hypothesis
    for previous_slot, node1 in previous_pattern_hypothesis.template_variable_to_pattern_node.items()
  File "/home/paynesa/adam/adam/learner/perception_graph_template.py", line 148, in intersection
    trim_after_match=trim_after_match,
  File "/home/paynesa/adam/adam/perception/perception_graph.py", line 1040, in intersection
    trim_after_match=trim_after_match,
  File "/home/paynesa/adam/adam/perception/perception_graph.py", line 1323, in relax_pattern_until_it_matches
    initial_partial_match=partial_match,
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/more_itertools/more.py", line 138, in first
    return next(iter(iterable))
  File "/home/paynesa/adam/adam/perception/perception_graph.py", line 1432, in _internal_matches
    initial_partial_match=merged_initial_partial_match,
  File "/home/paynesa/adam/adam/perception/_matcher.py", line 544, in subgraph_monomorphisms_iter
    self.initialize(initial_partial_match=initial_partial_match)
  File "/home/paynesa/adam/adam/perception/_matcher.py", line 204, in initialize
    self._jump_to_partial_match(initial_partial_match)
  File "/home/paynesa/adam/adam/perception/_matcher.py", line 264, in _jump_to_partial_match
    if not self.semantic_feasibility(aligned_graph_node, pattern_node):
  File "/home/paynesa/adam/adam/perception/_matcher.py", line 442, in semantic_feasibility
    for pattern_predecessor in self.pattern.pred[pattern_node]:
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/networkx/classes/coreviews.py", line 81, in __getitem__
    return AtlasView(self._atlas[name])
KeyError: ObjectSemanticNodePerceptionPredicate()```

This isn't encountered at the beginning of the curriculum, so it seems that it's an issue with this specific instance ("a green chair"). I believe this may be a result of #946, which I will look into.

**Comment by paynesa** [comment]
For the attributes curriculum, the learning is extremely slow for non-`CHAIR` objects (up to 3-4 minutes on some instances, most of this time is spent in the graph matching). I believe that this is likely caused by the same problems as the one that caused us to do #946, as well as #962 since the relative runtimes for different objects are pretty similar. I know that this was caused by the recursive match running ad infinitum; I spent a couple weeks trying to debug this without much luck and Ryan suggested just going with the param files that don't hang but if someone else more familiar with the matching algorithms feels like they can take a shot at it (@LichMaster98 or @spigo900?) I think that solving whatever is causing this would probably solve #946, #963, and #962, which would be great! 

If we skip attribute learning and go straight to relations, we end up with the following runtime error: 
```
Traceback (most recent call last):
  File "/home/paynesa/adam/adam/experiment/log_experiment.py", line 391, in <module>
    parameters_only_entry_point(log_experiment_entry_point)
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/vistautils/parameters_only_entrypoint.py", line 43, in parameters_only_entry_point
    args=sys.argv[1:],
  File "/home/paynesa/miniconda3/envs/adam/lib/python3.6/site-packages/vistautils/parameters_only_entrypoint.py", line 73, in _real_parameters_only_entry_point
    main_method(params)
  File "/home/paynesa/adam/adam/experiment/log_experiment.py", line 144, in log_experiment_entry_point
    load_learner_state=params.optional_existing_file("learner_state_path"),
  File "/home/paynesa/adam/adam/experiment/__init__.py", line 252, in execute_experiment
    offset=starting_point,
  File "/home/paynesa/adam/adam/learner/integrated_learner.py", line 126, in observe
    sub_learner.learn_from(current_learner_state, offset=offset)
  File "/home/paynesa/adam/adam/learner/template_learner.py", line 294, in learn_from
    language_perception_semantic_alignment
  File "/home/paynesa/adam/adam/learner/attributes.py", line 99, in _candidate_templates
    language_mode=self._language_mode,
  File "/home/paynesa/adam/adam/learner/alignments.py", line 264, in to_surface_template
    "We currently only allow for the situation "
RuntimeError: We currently only allow for the situation where every matched object corresponds to a template node.
```

but this may just be a result of the issues with graph matching that we already are having.

**Comment by spigo900** [comment]
@paynesa Is the attribute curriculum also slow using the object recognizer? If not, the slowdown might be related to some issues with how we do hypothesis intersection which I've fixed on #939.

**Comment by LichMaster98** [comment]
This issue is still present and blocks learning verbs due to a difference in static and dynamic pattern edges.
